---
- hosts: 172.31.19.19
  become: yes
  vars:
    my_variable: "Hello, World!"
    another_variable: 42

  tasks:
  - include_tasks: myfile.yml
  - name: install webserver on ubuntu
    apt:
      name: apache2
      state: present
  - name: copy a static file into the node side
    copy:
      src: mystaticfile
      dest: /home/maha/myfolder
  - name: Download a file from the internet
    get_url:
      url: https://updates.jenkins.io/download/war/2.583/jenkins.war
      dest: /home/maha/myfolder/jenkins.war
      force_basic_auth: yes
      