---
- hosts: 172.31.19.19
  become: yes
  vars:
    ansible_user: ec2-user
    myvar01: git
    myvar02: tree
    myvar03: wget
    ansible_ssh_private_key_file: /path/to/your/private/key.pem
  tasks:
    - name: I want to display myvar01
      debug:
        msg: "The value of myvar01 is {{ myvar01 }}"