---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks: 
  - name: i want to install webserver on this task01 (apt-get install apache2 -y )
    apt:
      name: "{{mywebpackondebaion}}"
      state: present 
    when: ansible_os_family=="Debian"


  - name: i want to start webserver on this task02 (service apache2 start)
    service:
      name: "{{mywebpackondebaion}}"
      state: started
    when: ansible_os_family=="Debian"

  - name: i want to install webserver on ansible RedHat nodes (yum install httpd -y)
    yum:
      name: "{{mywebpackonredhat}}"
      state: present
    when: ansible_os_family=="RedHat"  
  
  - name: i want to start websever on ansible RedHat nodes ( service httpd start)
    service:
       name: "{{mywebpackonredhat}}"
       state: started
    when: ansible_os_family =="RedHat"
