
---
- name: "Set permissions for Tomcat directories"
  command: "chown -R tomcat:tomcat /opt/tomcat/apache-tomcat-10.1.60"
  become: yes

- name: change execute permissions
  shell: "chmod +x /opt/tomcat/apache-tomcat-10.1.60/bin/*.sh"
  become: yes
